//___FILEHEADER___

import Foundation

protocol ___FILEBASENAMEASIDENTIFIER___VMInput {
    
}

protocol ___FILEBASENAMEASIDENTIFIER___VMOutput {
    
}

protocol ___FILEBASENAMEASIDENTIFIER___VM: ___FILEBASENAMEASIDENTIFIER___VMInput, ___FILEBASENAMEASIDENTIFIER___VMOutput {}

class ___FILEBASENAMEASIDENTIFIER___Impl: ___FILEBASENAMEASIDENTIFIER___VM {

}
